"""colocando senha do usuário pra 128 bits

Revision ID: 8055177a43ff
Revises: a145d4eb50cb
Create Date: 2026-02-12 20:02:16.614865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8055177a43ff'
down_revision: Union[str, Sequence[str], None] = 'a145d4eb50cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
